[Playground] [Backend] Sharing any code
akvelon/beam pull request #183
Opened 2022-06-22 15:18 UTC by vchunikhin

**Please** add a meaningful description for your change here
@konstantinurysov 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

2022-06-22 16:42 UTC, VladMatyunin commented on playground/backend/start_datastore_emulator.sh
> +#!/bin/bash
Please move the files for CI/CD to a separate PR

2022-06-22 16:42 UTC, VladMatyunin commented on playground/backend/internal/db/schema/migration/initial_structure.go
> +		Go     *SdkProperties `yaml:"SDK_GO"`
Please explore whether we can move that to a separate global struct

2022-06-23 07:16 UTC, konstantinurysov requested changes

2022-06-23 07:16 UTC, konstantinurysov commented on playground/backend/internal/db/local/local_db.go
> +		l.RUnlock()
what was the reason for not using defer here?

2022-06-23 07:16 UTC, konstantinurysov commented on playground/backend/internal/db/local/local_db_test.go
> +		panic(err)
please use panic only if it is inevitable
https://github.com/uber-go/guide/blob/master/style.md#dont-panic

2022-06-23 07:16 UTC, konstantinurysov commented on playground/backend/internal/utils/file_utils.go
> +	return name
nit: can be moved to default case

2022-06-23 07:16 UTC, konstantinurysov commented on playground/backend/internal/utils/file_utils.go
> +	} else {
nit: else can be removed

2022-06-23 07:16 UTC, konstantinurysov commented on playground/backend/internal/utils/file_utils.go
> +	return false
nit: can be moved to the default case

2022-06-23 07:18 UTC, konstantinurysov commented on playground/backend/cmd/server/controller_test.go
> +		panic(err)
please use panic only if it is inevitable, just double check that we cannot replace it with other options
https://github.com/uber-go/guide/blob/master/style.md#dont-panic

2022-07-06 05:55 UTC, closed without merging