BEAM-12967 Example Selector widget
akvelon/beam pull request #30
Opened 2021-10-05 16:44 UTC by miamihotline

Added Example Selector widget

2021-10-05 19:02 UTC, ElessarST requested changes

2021-10-05 19:02 UTC, ElessarST commented on playground/frontend/lib/modules/examples/components/search_field/search_field.dart
> +    final OutlineInputBorder _border = OutlineInputBorder(
should be without `_`. Please check all your variables.

2021-10-05 19:02 UTC, ElessarST commented on playground/frontend/lib/modules/examples/example_selector.dart
> +      duration: const Duration(milliseconds: 80),
move values to consts on the top of the file, please. (80, 0.0, 0.02 ...)

2021-10-05 19:02 UTC, ElessarST commented on playground/frontend/lib/modules/examples/models/category_model.dart
> +}
missing new line

2021-10-06 10:51 UTC, miamihotline commented on playground/frontend/lib/modules/examples/components/example_list/expansion_panel_item.dart
> +        child: Row(
Yes, but i guess we shouldn't, because when we choose example it's better to click on the full Row, than on the concrete Text widget.

2021-10-06 10:54 UTC, miamihotline commented on playground/frontend/lib/modules/examples/components/example_list/expansion_panel_item.dart
> +      onTap: () {},
Yes, not implemented yet :(

2021-10-06 11:21 UTC, closed without merging