Issue25483 pipeline options refactoring
akvelon/beam pull request #455
Opened 2023-04-12 12:45 UTC by Malarg

pipeline options extracted to playground_components and added to tour of beam

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[![Go tests](https://github.com/apache/beam/workflows/Go%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

2023-04-12 13:07 UTC, alexeyinkin commented on playground/frontend/playground_components/lib/src/widgets/pipeline_options_dropdown/pipeline_options_dropdown_separator.dart
>  class PipelineOptionsDropdownSeparator extends StatelessWidget {
Can we reuse `BeamDivider` for this?

2023-04-12 13:08 UTC, alexeyinkin commented on playground/frontend/playground_components/lib/src/widgets/pipeline_options_dropdown/pipeline_options_row.dart
> +              color: BeamLightThemeColors.primary, //Color(0xFFE74D1A)
How about the dark theme?

2023-04-13 08:41 UTC, Malarg commented on learning/tour-of-beam/frontend/lib/components/scaffold.dart
> +  final TourNotifier? tourNotifier;
fixed

2023-04-13 08:41 UTC, Malarg commented on playground/frontend/playground_components/lib/src/constants/constants.dart
> +const double kLabelFontSize = 16.0;
fixed

2023-04-13 08:42 UTC, Malarg commented on playground/frontend/playground_components/lib/src/widgets/pipeline_options_dropdown/pipeline_options_dropdown.dart
> +import '../dropdown_button/dropdown_button.dart';
done

2023-04-13 08:42 UTC, Malarg commented on playground/frontend/playground_components/lib/src/widgets/pipeline_options_dropdown/pipeline_options_dropdown_separator.dart
>  class PipelineOptionsDropdownSeparator extends StatelessWidget {
Yes, done

2023-04-13 08:42 UTC, Malarg commented on playground/frontend/playground_components/lib/src/widgets/pipeline_options_dropdown/pipeline_options_row.dart
> +              color: BeamLightThemeColors.primary, //Color(0xFFE74D1A)
Correct, done

2023-04-13 10:46 UTC, alexeyinkin requested changes

2023-04-13 10:46 UTC, alexeyinkin commented on learning/tour-of-beam/frontend/lib/pages/tour/widgets/pipeline_options.dart
> +  final TourNotifier tourNotifier;
PlaygroundController is sufficient for this.

2023-04-13 10:46 UTC, alexeyinkin commented on learning/tour-of-beam/frontend/lib/pages/tour/widgets/playground_demo.dart
> +    controller.resetErrorMessageText();
Check if there is an issue to refactor this. Link in a TODO.

2023-04-13 10:46 UTC, alexeyinkin commented on playground/frontend/playground_components/lib/src/constants/sizes.dart
> +  static const double labelFontSize = 16;
Delete.

2023-04-18 10:42 UTC, alexeyinkin requested changes

2023-04-18 10:42 UTC, alexeyinkin commented on learning/tour-of-beam/frontend/lib/pages/tour/screen.dart
> +          playgroundController: tourNotifier.playgroundController,
Put `TobScaffold` into AnimatedBuilder. Pass `null` for `playgroundController` if there is no snippet for the unit.

2023-04-18 10:42 UTC, alexeyinkin commented on playground/frontend/playground_components/lib/src/controllers/playground_controller.dart
> +  void setEmpty() {
Delete.

2023-04-18 15:45 UTC, alexeyinkin requested changes

2023-04-18 15:45 UTC, alexeyinkin commented on learning/tour-of-beam/frontend/lib/pages/tour/state.dart
> +  PlaygroundController? playgroundController;
TourNotifier must always have a `final PlaygroundController`.
When I talked nullable, I meant that `TobScaffold.playgroundController` should be `null`.

2023-04-18 15:45 UTC, alexeyinkin commented on learning/tour-of-beam/frontend/lib/components/scaffold.dart
Revert please.

2023-04-21 04:19 UTC, alexeyinkin requested changes

2023-04-21 04:19 UTC, alexeyinkin commented on playground/frontend/playground_components/lib/src/controllers/playground_controller.dart
> +import '../models/snippet_file.dart';
Unused.

2023-04-21 04:19 UTC, alexeyinkin commented on playground/frontend/playground_components/lib/src/controllers/example_loaders/examples_loader.dart
> +
Delete.

2023-04-21 04:19 UTC, alexeyinkin commented on learning/tour-of-beam/frontend/lib/components/scaffold.dart
> +              .toList(),
```suggestion
              .toList(growable: false),
```

2023-04-21 09:16 UTC, alexeyinkin approved these changes
LGTM (internal review).

2023-04-21 12:15 UTC, merged